### ISSUE TITLE
Build 出apk安装之后还是显示1.9.0版本

### ISSUE THREAD

**Issue by geek981108** [Blankeer/MDWechat#26]
从作者源码Build 出apk安装之后还是显示1.9.0版本，且微信6.6.7版本无效，设备为一加5 ，Android API 28，求解决

**Comment by Blankeer** [comment]
已上传最新代码。打开调试日志开关，提交日志看看

**Comment by geek981108** [comment]
新版本Build成功，安装后可以运行，发现了几个问题：
1.右下角加号内的选项点击后全部出现“跳转失败，请检查类名是否正确”
2.部分页面顶栏类似乱码
```
19:30:21 MDWechat:	LauncherUI onResume(), start hook
19:30:21 MDWechat:	移除 tabView com.tencent.mm.ui.LauncherUIBottomTabView{271308e V.E...... ......I. 0,0-0,0}
19:30:21 MDWechat:	添加 TabLayout
19:30:21 MDWechat:	add tableyout success
19:30:21 MDWechat:	添加 FloatMenu
19:30:21 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg0.png (No such file or directory)
19:30:21 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg2.png (No such file or directory)
19:30:21 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg3.png (No such file or directory)
19:30:22 MDWechat:	检测到 微X模块
19:30:22 MDWechat:	检测到 微X模块
19:30:27 MDWechat:	LauncherUI onResume(), start hook
19:30:27 MDWechat:	移除 tabView com.tencent.mm.ui.LauncherUIBottomTabView{3e29130 V.E...... ......I. 0,0-0,0}
19:30:27 MDWechat:	添加 TabLayout
19:30:27 MDWechat:	add tableyout success
19:30:27 MDWechat:	添加 FloatMenu
19:30:27 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg0.png (No such file or directory)
19:30:27 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg2.png (No such file or directory)
19:30:27 Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/mdwechat/icon/tab_bg3.png (No such file or directory)
19:30:27 MDWechat:	检测到 微X模块
19:30:27 MDWechat:	检测到 微X模块
19:30:28 MDWechat:	检测到 微X模块
19:30:28 MDWechat:	检测到 微X模块
19:30:28 MDWechat:	ContactFragment 已经hook过
19:30:28 MDWechat:	ContactFragment 已经hook过
19:30:29 MDWechat:	检测到 微X模块
19:30:30 MDWechat:	点击悬浮按钮，index=3,item=FLoatButtonConfigItem(order=4, type=addfriend, icon=ic_person_add.png, text=添加好友)
19:30:30 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/addfriend}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:30:31 MDWechat:	ContactFragment 已经hook过
19:30:31 MDWechat:	ContactFragment 已经hook过
19:31:02 MDWechat:	LauncherUI 已经hook过
19:31:02 MDWechat:	ContactFragment 已经hook过
19:31:02 MDWechat:	DiscoverFragment 已经hook过
19:31:02 MDWechat:	SettingsFragment 已经hook过
19:31:02 MDWechat:	ConversationFragment 已经hook过
19:31:03 MDWechat:	点击悬浮按钮，index=3,item=FLoatButtonConfigItem(order=4, type=addfriend, icon=ic_person_add.png, text=添加好友)
19:31:03 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/addfriend}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:31:04 MDWechat:	点击悬浮按钮，index=2,item=FLoatButtonConfigItem(order=3, type=chatgroup, icon=ic_chat.png, text=群聊)
19:31:04 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/chatgroup}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:31:06 MDWechat:	点击悬浮按钮，index=1,item=FLoatButtonConfigItem(order=2, type=scan, icon=ic_scan.png, text=扫一扫)
19:31:06 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/scan}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:31:07 MDWechat:	点击悬浮按钮，index=0,item=FLoatButtonConfigItem(order=1, type=walletcoin, icon=ic_money.png, text=收付款)
19:31:07 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/walletcoin}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:31:08 MDWechat:	检测到 微X模块
19:31:08 MDWechat:	检测到 微X模块
19:31:10 MDWechat:	检测到 微X模块
19:31:10 MDWechat:	检测到 微X模块
19:31:12 MDWechat:	ContactFragment 已经hook过
19:31:12 MDWechat:	ContactFragment 已经hook过
19:31:38 MDWechat:	LauncherUI 已经hook过
19:31:38 MDWechat:	DiscoverFragment 已经hook过
19:31:38 MDWechat:	SettingsFragment 已经hook过
19:31:38 MDWechat:	ConversationFragment 已经hook过
19:31:38 MDWechat:	检测到 微X模块
19:31:39 MDWechat:	检测到 微X模块
19:31:40 MDWechat:	检测到 微X模块
19:31:40 MDWechat:	检测到 微X模块
19:31:40 MDWechat:	检测到 微X模块
19:31:40 MDWechat:	检测到 微X模块
19:31:40 MDWechat:	检测到 微X模块
19:31:41 MDWechat:	ContactFragment 已经hook过
19:33:42 MDWechat:	LauncherUI 已经hook过
19:33:42 MDWechat:	DiscoverFragment 已经hook过
19:33:42 MDWechat:	SettingsFragment 已经hook过
19:33:42 MDWechat:	ConversationFragment 已经hook过
19:33:43 MDWechat:	点击悬浮按钮，index=3,item=FLoatButtonConfigItem(order=4, type=addfriend, icon=ic_person_add.png, text=添加好友)
19:33:43 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.mm/addfriend}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2124)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
	at android.app.Activity.startActivityForResult(Activity.java:4514)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:504)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:842)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:494)
	at android.app.Activity.startActivity(Activity.java:4833)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:488)
	at android.app.Activity.startActivity(Activity.java:4801)
	at com.tencent.mm.ui.MMFragmentActivity.startActivity(SourceFile:481)
	at com.blanke.mdwechat.WeChatHelper.startActivity(WeChatHelper.kt:95)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.onFloatButtonClick(FloatMenuHook.kt:144)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook.access$onFloatButtonClick(FloatMenuHook.kt:24)
	at com.blanke.mdwechat.hookers.main.FloatMenuHook$addFloatMenu$3.onClick(FloatMenuHook.kt:61)
	at com.github.clans.fab.FloatingActionMenu$10.onClick(FloatingActionMenu.java:991)
	at android.view.View.performClick(View.java:6367)
	at android.view.View$PerformClick.run(View.java:25032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

19:33:44 MDWechat:	ContactFragment 已经hook过
```
[MDWechat_log_2018-07-06.txt](https://github.com/Blankeer/MDWechat/files/2170348/MDWechat_log_2018-07-06.txt)
![screenshot_20180706-192949](https://user-images.githubusercontent.com/28996049/42377373-acea8ebe-8155-11e8-996e-505c1a7512a6.jpg)
![screenshot_20180706-192951](https://user-images.githubusercontent.com/28996049/42377374-ad52d2c6-8155-11e8-959b-fdd1eb8f907d.jpg)
![screenshot_20180706-193127__01](https://user-images.githubusercontent.com/28996049/42377375-adb9c756-8155-11e8-9a38-101bffeb86f0.jpg)

**Comment by Blankeer** [comment]
悬浮按钮type 需要完整类名，具体看酷安动态说明

**Comment by geek981108** [comment]
十分感谢，FloatButton已正常，但是顶栏乱码还是存在的

**Comment by Blankeer** [comment]
主色有透明度会出现此现象

**Comment by geek981108** [comment]
明白了，十分感谢
