### ISSUE TITLE
微信6.7.2强制关闭

### ISSUE THREAD

**Issue by Xiphoray** [Blankeer/MDWechat#47]
开启模块后打开微信会提示微信停止运行
另外，关闭总开关后微信能正常运行

安卓8.1
机型  红米 5plus
MDWechat  3.1.0 (3.0.0也有同样问题)
Xposed 环境及版本 90beta3
微信版本 6.7.2

以下为 logcat
```
09-13 10:20:14.155 4812-4812/? A/zygote: quick_exception_handler.cc:326] Check failed: callee_method_ != nullptr com.blanke.mdwechat.WechatHook.hookMain
09-13 10:20:14.231 4812-4812/? A/zygote: runtime.cc:528] Runtime aborting...
    runtime.cc:528] Dumping all threads without appropriate locks held: thread list lock
    runtime.cc:528] All threads:
    runtime.cc:528] DALVIK THREADS (11):
    runtime.cc:528] "main" prio=10 tid=1 Runnable
    runtime.cc:528]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71b5e2b0 self=0xecfde000
    runtime.cc:528]   | sysTid=4812 nice=-10 cgrp=default sched=0/0 handle=0xf34174a4
    runtime.cc:528]   | state=R schedstat=( 712429015 11740780 147 ) utm=67 stm=4 core=4 HZ=100
    runtime.cc:528]   | stack=0xff2a2000-0xff2a4000 stackSize=8MB
    runtime.cc:528]   | held mutexes= "abort lock" "mutator lock"(shared held)
    runtime.cc:528]   native: #00 pc 002f2bb7  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*)+130)
    runtime.cc:528]   native: #01 pc 0038ac8f  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+206)
    runtime.cc:528]   native: #02 pc 00387207  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
    runtime.cc:528]   native: #03 pc 0039f43b  /system/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+718)
    runtime.cc:528]   native: #04 pc 00398eb9  /system/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+320)
    runtime.cc:528]   native: #05 pc 00398831  /system/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+160)
    runtime.cc:528]   native: #06 pc 00377b67  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&) const+210)
    runtime.cc:528]   native: #07 pc 0036ac3b  /system/lib/libart.so (art::Runtime::Abort(char const*)+142)
    runtime.cc:528]   native: #08 pc 0042e07f  /system/lib/libart.so (android::base::LogMessage::~LogMessage()+454)
    runtime.cc:528]   native: #09 pc 00361e19  /system/lib/libart.so (art::DeoptimizeStackVisitor::FinishStackWalk()+208)
    runtime.cc:528]   native: #10 pc 00361a6f  /system/lib/libart.so (art::DeoptimizeStackVisitor::VisitFrame()+42)
    runtime.cc:528]   native: #11 pc 0037d647  /system/lib/libart.so (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+822)
    runtime.cc:528]   native: #12 pc 00361143  /system/lib/libart.so (art::QuickExceptionHandler::DeoptimizeStack()+62)
    runtime.cc:528]   native: #13 pc 003ebe69  /system/lib/libart.so (art::artDeoptimizeImpl(art::Thread*, art::DeoptimizationKind, bool)+452)
    runtime.cc:528]   native: #14 pc 003ebca1  /system/lib/libart.so (artDeoptimize+6)
    runtime.cc:528]   native: #15 pc 00418c5d  /system/lib/libart.so (art_quick_deoptimize+28)
    runtime.cc:528]   native: #16 pc 000fabe5  /data/dalvik-cache/arm/data@app@com.blanke.mdwechat-XyoTtyMo7d7SSNEyqp5Lyg==@base.apk@classes.dex (???)
    runtime.cc:528]   at com.blanke.mdwechat.WechatHook.hookMain(WechatHook.kt:63)
    runtime.cc:528]   at com.blanke.mdwechat.WechatHook.handleLoadPackage(WechatHook.kt:43)
    runtime.cc:528]   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-13 10:20:14.232 4812-4812/? A/zygote: runtime.cc:528]   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
    runtime.cc:528]   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
    runtime.cc:528]   at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
    runtime.cc:528]   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
    runtime.cc:528]   at android.app.ActivityThread.handleBindApplication [XposedHooked](<Xposed>:-2)
    runtime.cc:528]   at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
    runtime.cc:528]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    runtime.cc:528]   at android.os.Handler.dispatchMessage(Handler.java:106)
    runtime.cc:528]   at android.os.Looper.loop(Looper.java:164)
    runtime.cc:528]   at android.app.ActivityThread.main(ActivityThread.java:6494)
    runtime.cc:528]   at java.lang.reflect.Method.invoke(Native method)
    runtime.cc:528]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    runtime.cc:528]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    runtime.cc:528]   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
    runtime.cc:528] 
    runtime.cc:528] "Jit thread pool worker thread 0" prio=10 tid=2 Native
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x10700000 self=0xe71a0000
    runtime.cc:528]   | sysTid=4817 nice=9 cgrp=default sched=0/0 handle=0xe717f970
    runtime.cc:528]   | state=S schedstat=( 4750883 300783 44 ) utm=0 stm=0 core=5 HZ=100
    runtime.cc:528]   | stack=0xe7081000-0xe7083000 stackSize=1022KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4817/stack)
    runtime.cc:528]   native: #00 pc 00018d6c  /system/lib/libc.so (syscall+28)
    runtime.cc:528]   native: #01 pc 000b96e9  /system/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+88)
    runtime.cc:528]   native: #02 pc 003a06e1  /system/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+172)
    runtime.cc:528]   native: #03 pc 003a004b  /system/lib/libart.so (art::ThreadPoolWorker::Run()+62)
    runtime.cc:528]   native: #04 pc 0039fc61  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+92)
    runtime.cc:528]   native: #05 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #06 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
    runtime.cc:528] 
    runtime.cc:528] "Signal Catcher" prio=10 tid=3 WaitingInMainSignalCatcherLoop
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x107000b0 self=0xecfdec00
    runtime.cc:528]   | sysTid=4818 nice=0 cgrp=default sched=0/0 handle=0xe707e970
    runtime.cc:528]   | state=S schedstat=( 366979 0 1 ) utm=0 stm=0 core=6 HZ=100
    runtime.cc:528]   | stack=0xe6f84000-0xe6f86000 stackSize=1006KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4818/stack)
    runtime.cc:528]   native: #00 pc 000497e4  /system/lib/libc.so (__rt_sigtimedwait+12)
    runtime.cc:528]   native: #01 pc 00020b2b  /system/lib/libc.so (sigwait+34)
    runtime.cc:528]   native: #02 pc 0037d28b  /system/lib/libart.so (art::SignalSet::Wait()+22)
    runtime.cc:528]   native: #03 pc 0037cea9  /system/lib/libart.so (art::SignalCatcher::WaitForSignal(art::Thread*, art::SignalSet&)+184)
    runtime.cc:528]   native: #04 pc 0037bb09  /system/lib/libart.so (art::SignalCatcher::Run(void*)+184)
    runtime.cc:528]   native: #05 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #06 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
    runtime.cc:528] 
    runtime.cc:528] "ReferenceQueueDaemon" prio=10 tid=4 Waiting
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x10700148 self=0xe6edb400
    runtime.cc:528]   | sysTid=4819 nice=4 cgrp=default sched=0/0 handle=0xd0bbe970
    runtime.cc:528]   | state=S schedstat=( 1576666 84583 14 ) utm=0 stm=0 core=4 HZ=100
    runtime.cc:528]   | stack=0xd0abc000-0xd0abe000 stackSize=1038KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4819/stack)
    runtime.cc:528]   native: #00 pc 00018d6c  /system/lib/libc.so (syscall+28)
    runtime.cc:528]   native: #01 pc 000b96e9  /system/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+88)
    runtime.cc:528]   native: #02 pc 002eee85  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, long long, int, bool, art::ThreadState)+524)
    runtime.cc:528]   native: #03 pc 002f03ab  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, art::mirror::Object*, long long, int, bool, art::ThreadState)+174)
    runtime.cc:528]   native: #04 pc 00301613  /system/lib/libart.so (art::Object_wait(_JNIEnv*, _jobject*)+32)
    runtime.cc:528]   native: #05 pc 0000053b  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__+74)
    runtime.cc:528]   at java.lang.Object.wait(Native method)
    runtime.cc:528]   - waiting on <0x0bfdbf42> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
    runtime.cc:528]   at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
    runtime.cc:528]   - locked <0x0bfdbf42> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
    runtime.cc:528]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    runtime.cc:528]   at java.lang.Thread.run(Thread.java:764)
    runtime.cc:528] 
    runtime.cc:528] "FinalizerDaemon" prio=10 tid=5 Waiting
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x107001d0 self=0xe6edba00
    runtime.cc:528]   | sysTid=4820 nice=4 cgrp=default sched=0/0 handle=0xd0ab9970
    runtime.cc:528]   | state=S schedstat=( 1851460 2772395 15 ) utm=0 stm=0 core=6 HZ=100
    runtime.cc:528]   | stack=0xd09b7000-0xd09b9000 stackSize=1038KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4820/stack)
    runtime.cc:528]   native: #00 pc 00018d6c  /system/lib/libc.so (syscall+28)
09-13 10:20:14.233 4812-4812/? A/zygote: runtime.cc:528]   native: #01 pc 000b96e9  /system/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+88)
    runtime.cc:528]   native: #02 pc 002eee85  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, long long, int, bool, art::ThreadState)+524)
    runtime.cc:528]   native: #03 pc 002f03ab  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, art::mirror::Object*, long long, int, bool, art::ThreadState)+174)
    runtime.cc:528]   native: #04 pc 0030163f  /system/lib/libart.so (art::Object_waitJI(_JNIEnv*, _jobject*, long long, int)+36)
    runtime.cc:528]   native: #05 pc 0000081d  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+92)
    runtime.cc:528]   at java.lang.Object.wait(Native method)
    runtime.cc:528]   - waiting on <0x0a5cbb53> (a java.lang.Object)
    runtime.cc:528]   at java.lang.Object.wait(Object.java:422)
    runtime.cc:528]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
    runtime.cc:528]   - locked <0x0a5cbb53> (a java.lang.Object)
    runtime.cc:528]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
    runtime.cc:528]   at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
    runtime.cc:528]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    runtime.cc:528]   at java.lang.Thread.run(Thread.java:764)
    runtime.cc:528] 
    runtime.cc:528] "FinalizerWatchdogDaemon" prio=10 tid=6 Sleeping
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x10700318 self=0xe5360000
    runtime.cc:528]   | sysTid=4821 nice=4 cgrp=default sched=0/0 handle=0xd09b4970
    runtime.cc:528]   | state=S schedstat=( 640833 2007761 17 ) utm=0 stm=0 core=5 HZ=100
    runtime.cc:528]   | stack=0xd08b2000-0xd08b4000 stackSize=1038KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4821/stack)
    runtime.cc:528]   native: #00 pc 00018d70  /system/lib/libc.so (syscall+32)
    runtime.cc:528]   native: #01 pc 000b9a11  /system/lib/libart.so (art::ConditionVariable::TimedWait(art::Thread*, long long, int)+108)
    runtime.cc:528]   native: #02 pc 002eee95  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, long long, int, bool, art::ThreadState)+540)
    runtime.cc:528]   native: #03 pc 002f03ab  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, art::mirror::Object*, long long, int, bool, art::ThreadState)+174)
    runtime.cc:528]   native: #04 pc 00306e01  /system/lib/libart.so (art::Thread_sleep(_JNIEnv*, _jclass*, _jobject*, long long, int)+56)
    runtime.cc:528]   native: #05 pc 000184f7  /system/framework/arm/boot.oat (Java_java_lang_Thread_sleep__Ljava_lang_Object_2JI+142)
    runtime.cc:528]   at java.lang.Thread.sleep(Native method)
    runtime.cc:528]   - sleeping on <0x0fc13c90> (a java.lang.Object)
    runtime.cc:528]   at java.lang.Thread.sleep(Thread.java:373)
    runtime.cc:528]   - locked <0x0fc13c90> (a java.lang.Object)
    runtime.cc:528]   at java.lang.Thread.sleep(Thread.java:314)
    runtime.cc:528]   at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342)
    runtime.cc:528]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364)
    runtime.cc:528]   at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281)
    runtime.cc:528]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    runtime.cc:528]   at java.lang.Thread.run(Thread.java:764)
    runtime.cc:528] 
    runtime.cc:528] "HeapTaskDaemon" prio=10 tid=7 Blocked
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x107005c8 self=0xe5360600
    runtime.cc:528]   | sysTid=4822 nice=4 cgrp=default sched=0/0 handle=0xd08af970
    runtime.cc:528]   | state=S schedstat=( 81054205 1507972 47 ) utm=7 stm=0 core=7 HZ=100
    runtime.cc:528]   | stack=0xd07ad000-0xd07af000 stackSize=1038KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4822/stack)
    runtime.cc:528]   native: #00 pc 00018d70  /system/lib/libc.so (syscall+32)
    runtime.cc:528]   native: #01 pc 000b9a11  /system/lib/libart.so (art::ConditionVariable::TimedWait(art::Thread*, long long, int)+108)
    runtime.cc:528]   native: #02 pc 001d1d65  /system/lib/libart.so (art::gc::TaskProcessor::GetTask(art::Thread*)+240)
    runtime.cc:528]   native: #03 pc 001d236d  /system/lib/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+44)
    runtime.cc:528]   native: #04 pc 00193e2b  /system/framework/arm/boot-core-libart.oat (Java_dalvik_system_VMRuntime_runHeapTasks__+74)
    runtime.cc:528]   at dalvik.system.VMRuntime.runHeapTasks(Native method)
    runtime.cc:528]   - waiting to lock an unknown object
    runtime.cc:528]   at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:461)
    runtime.cc:528]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    runtime.cc:528]   at java.lang.Thread.run(Thread.java:764)
    runtime.cc:528] 
    runtime.cc:528] "Binder:4812_1" prio=10 tid=8 Native
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x107004b8 self=0xe71a3c00
    runtime.cc:528]   | sysTid=4823 nice=0 cgrp=default sched=0/0 handle=0xd06ac970
    runtime.cc:528]   | state=S schedstat=( 761512 74687 15 ) utm=0 stm=0 core=7 HZ=100
    runtime.cc:528]   | stack=0xd05b2000-0xd05b4000 stackSize=1006KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4823/stack)
    runtime.cc:528]   native: #00 pc 000495f0  /system/lib/libc.so (__ioctl+8)
    runtime.cc:528]   native: #01 pc 0001dde9  /system/lib/libc.so (ioctl+32)
    runtime.cc:528]   native: #02 pc 00042757  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+202)
    runtime.cc:528]   native: #03 pc 00042861  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+8)
    runtime.cc:528]   native: #04 pc 00042db3  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+38)
    runtime.cc:528]   native: #05 pc 00058685  /system/lib/libbinder.so (???)
    runtime.cc:528]   native: #06 pc 0000d1b9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+144)
    runtime.cc:528]   native: #07 pc 0006dce1  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+80)
    runtime.cc:528]   native: #08 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #09 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
09-13 10:20:14.234 4812-4812/? A/zygote: runtime.cc:528] 
    runtime.cc:528] "Binder:4812_2" prio=10 tid=9 Native
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0x10700540 self=0xe537d000
    runtime.cc:528]   | sysTid=4824 nice=0 cgrp=default sched=0/0 handle=0xd05af970
    runtime.cc:528]   | state=S schedstat=( 4373225 1457395 21 ) utm=0 stm=0 core=4 HZ=100
    runtime.cc:528]   | stack=0xd04b5000-0xd04b7000 stackSize=1006KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4824/stack)
    runtime.cc:528]   native: #00 pc 000495f0  /system/lib/libc.so (__ioctl+8)
    runtime.cc:528]   native: #01 pc 0001dde9  /system/lib/libc.so (ioctl+32)
    runtime.cc:528]   native: #02 pc 00042757  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+202)
    runtime.cc:528]   native: #03 pc 00042861  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+8)
    runtime.cc:528]   native: #04 pc 00042db3  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+38)
    runtime.cc:528]   native: #05 pc 00058685  /system/lib/libbinder.so (???)
    runtime.cc:528]   native: #06 pc 0000d1b9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+144)
    runtime.cc:528]   native: #07 pc 0006dce1  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+80)
    runtime.cc:528]   native: #08 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #09 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
    runtime.cc:528] 
    runtime.cc:528] "Binder:4812_3" prio=10 tid=10 Native
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0xf240000 self=0xe7195800
    runtime.cc:528]   | sysTid=4825 nice=0 cgrp=default sched=0/0 handle=0xd04b2970
    runtime.cc:528]   | state=S schedstat=( 494115 1338334 6 ) utm=0 stm=0 core=7 HZ=100
    runtime.cc:528]   | stack=0xd03b8000-0xd03ba000 stackSize=1006KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4825/stack)
    runtime.cc:528]   native: #00 pc 000495f0  /system/lib/libc.so (__ioctl+8)
    runtime.cc:528]   native: #01 pc 0001dde9  /system/lib/libc.so (ioctl+32)
    runtime.cc:528]   native: #02 pc 00042757  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+202)
    runtime.cc:528]   native: #03 pc 00042861  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+8)
    runtime.cc:528]   native: #04 pc 00042db3  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+38)
    runtime.cc:528]   native: #05 pc 00058685  /system/lib/libbinder.so (???)
    runtime.cc:528]   native: #06 pc 0000d1b9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+144)
    runtime.cc:528]   native: #07 pc 0006dce1  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+80)
    runtime.cc:528]   native: #08 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #09 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
    runtime.cc:528] 
    runtime.cc:528] "Profile Saver" prio=10 tid=11 Native
    runtime.cc:528]   | group="" sCount=1 dsCount=0 flags=1 obj=0xf240088 self=0xe6eebc00
    runtime.cc:528]   | sysTid=4826 nice=9 cgrp=default sched=0/0 handle=0xcb585970
    runtime.cc:528]   | state=S schedstat=( 400364 113595 4 ) utm=0 stm=0 core=4 HZ=100
    runtime.cc:528]   | stack=0xcb48b000-0xcb48d000 stackSize=1006KB
    runtime.cc:528]   | held mutexes=
    runtime.cc:528]   kernel: (couldn't read /proc/self/task/4826/stack)
    runtime.cc:528]   native: #00 pc 00018d70  /system/lib/libc.so (syscall+32)
    runtime.cc:528]   native: #01 pc 000b9a11  /system/lib/libart.so (art::ConditionVariable::TimedWait(art::Thread*, long long, int)+108)
    runtime.cc:528]   native: #02 pc 0027e43f  /system/lib/libart.so (art::ProfileSaver::Run()+142)
    runtime.cc:528]   native: #03 pc 002807e7  /system/lib/libart.so (art::ProfileSaver::RunProfileSaverThread(void*)+50)
    runtime.cc:528]   native: #04 pc 00047f3f  /system/lib/libc.so (???)
    runtime.cc:528]   native: #05 pc 0001afc9  /system/lib/libc.so (???)
    runtime.cc:528]   (no managed stack frames)
    runtime.cc:528] 
    runtime.cc:528] Aborting thread:
    runtime.cc:528] "main" prio=10 tid=1 Runnable
    runtime.cc:528]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71b5e2b0 self=0xecfde000
    runtime.cc:528]   | sysTid=4812 nice=-10 cgrp=default sched=0/0 handle=0xf34174a4
    runtime.cc:528]   | state=R schedstat=( 753134065 11740780 166 ) utm=70 stm=4 core=6 HZ=100
    runtime.cc:528]   | stack=0xff2a2000-0xff2a4000 stackSize=8MB
    runtime.cc:528]   | held mutexes= "abort lock" "mutator lock"(shared held)
    runtime.cc:528]   native: #00 pc 002f2bb7  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*)+130)
    runtime.cc:528]   native: #01 pc 0038ac8f  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+206)
    runtime.cc:528]   native: #02 pc 00387207  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
    runtime.cc:528]   native: #03 pc 00377fa5  /system/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, art::Thread*) const+28)
    runtime.cc:528]   native: #04 pc 0036ac3b  /system/lib/libart.so (art::Runtime::Abort(char const*)+142)
    runtime.cc:528]   native: #05 pc 0042e07f  /system/lib/libart.so (android::base::LogMessage::~LogMessage()+454)
    runtime.cc:528]   native: #06 pc 00361e19  /system/lib/libart.so (art::DeoptimizeStackVisitor::FinishStackWalk()+208)
    runtime.cc:528]   native: #07 pc 00361a6f  /system/lib/libart.so (art::DeoptimizeStackVisitor::VisitFrame()+42)
    runtime.cc:528]   native: #08 pc 0037d647  /system/lib/libart.so (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+822)
    runtime.cc:528]   native: #09 pc 00361143  /system/lib/libart.so (art::QuickExceptionHandler::DeoptimizeStack()+62)
    runtime.cc:528]   native: #10 pc 003ebe69  /system/lib/libart.so (art::artDeoptimizeImpl(art::Thread*, art::DeoptimizationKind, bool)+452)
    runtime.cc:528]   native: #11 pc 003ebca1  /system/lib/libart.so (artDeoptimize+6)
    runtime.cc:528]   native: #12 pc 00418c5d  /system/lib/libart.so (art_quick_deoptimize+28)
    runtime.cc:528]   native: #13 pc 000fabe5  /data/dalvik-cache/arm/data@app@com.blanke.mdwechat-XyoTtyMo7d7SSNEyqp5Lyg==@base.apk@classes.dex (???)
09-13 10:20:14.235 4812-4812/? A/zygote: runtime.cc:528]   at com.blanke.mdwechat.WechatHook.hookMain(WechatHook.kt:63)
    runtime.cc:528]   at com.blanke.mdwechat.WechatHook.handleLoadPackage(WechatHook.kt:43)
    runtime.cc:528]   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
    runtime.cc:528]   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
    runtime.cc:528]   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
    runtime.cc:528]   at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
    runtime.cc:528]   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
    runtime.cc:528]   at android.app.ActivityThread.handleBindApplication [XposedHooked](<Xposed>:-2)
    runtime.cc:528]   at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
    runtime.cc:528]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    runtime.cc:528]   at android.os.Handler.dispatchMessage(Handler.java:106)
    runtime.cc:528]   at android.os.Looper.loop(Looper.java:164)
    runtime.cc:528]   at android.app.ActivityThread.main(ActivityThread.java:6494)
    runtime.cc:528]   at java.lang.reflect.Method.invoke(Native method)
    runtime.cc:528]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    runtime.cc:528]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    runtime.cc:528]   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
    runtime.cc:528] 
09-13 10:20:14.289 4834-4834/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/8.5.9:user/release-keys'
    Revision: '0'
    ABI: 'arm'
    pid: 4812, tid: 4812, name: re-initialized>  >>> <pre-initialized> <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-13 10:20:14.293 4834-4834/? A/DEBUG: Abort message: 'quick_exception_handler.cc:326] Check failed: callee_method_ != nullptr com.blanke.mdwechat.WechatHook.hookMain'
        r0 00000000  r1 000012cc  r2 00000006  r3 00000008
        r4 000012cc  r5 000012cc  r6 ffa9e2f4  r7 0000010c
        r8 00000000  r9 0000000b  sl ffa9e41c  fp 00000000
        ip 0000000b  sp ffa9e2e0  lr f2379911  pc f23733fa  cpsr 200f0030
```

**Comment by jw8013** [comment]
[app.log](https://github.com/Blankeer/MDWechat/files/2381659/app.log)
额，抓了个安卓8.1微信play6.6.7闪退的包，麻烦大佬也看一下

**Comment by Blankeer** [comment]
目前没有解决方案。只能重启/重装尝试，再不行建议放弃吧。

**Comment by Darkpurple** [comment]
我Oneplus也同樣問題…不知道是不是跟Android 8.1有關…

**Comment by HackerGBD** [comment]
至今找不到原因，有解决的大佬么？
